### ISSUE TITLE
COQ 8.8.0 , Ocaml 4.0.5 , GCC 7.3

### ISSUE THREAD

**Issue by command-paul** [mit-plv/kami#3]
Am Running into the following errors trying to run the make files
```bash
TOP$ make

...

COQC Kami/Substitute.v
COQC Kami/Decomposition.v
COQC Kami/ModuleBound.v
COQC Kami/ParametricWf.v
File "./Kami/ParametricWf.v", line 281, characters 2-164:
Error:
Recursive definition of ValidRegsMetaModule is ill-formed.
In environment
type : Kind -> Type
ValidRegsMetaModule : MetaModule -> Prop
Recursive definition on "MetaModule"
which should be a recursive inductive type.
Recursive definition is:
"fun mm : MetaModule =>
 ValidRegsMetaRules (metaRegs mm) (metaRules mm) /\
 ValidRegsMetaMeths (metaRegs mm) (metaMeths mm)".

Makefile.coq.all:656: recipe for target 'Kami/ParametricWf.vo' failed
make[2]: *** [Kami/ParametricWf.vo] Error 1
Makefile.coq.all:317: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/scratch/kami'
Makefile:26: recipe for target 'coq' failed
make: *** [coq] Error 2

```
Additionally  , 
```bash
TOP/Kami/Ext/Ocaml$ make
ocamlbuild -use-ocamlfind Main.native
+ ocamlfind ocamlc -c -o PP.cmo PP.ml
File "PP.ml", line 2, characters 5-11:
Error: Unbound module Target
Command exited with code 2.
Compilation unsuccessful after building 3 targets (2 cached) in 00:00:00.
Makefile:9: recipe for target 'native' failed
make: *** [native] Error 10
```

Would Appreciate any support getting setup.

**Comment by vmurali** [comment]
Which branch did you use? The master branch does not compile with 8.8.0.
There's a separate 8.8.0 branch.

**Comment by command-paul** [comment]
I used the 8.8.0 branch for this.

**Comment by vmurali** [comment]
Try the dsss-18 branch since that was recently tested.

You can also try this repo, which is version 2 of Kami, which compiles with
the recent releases of Coq and is being actively maintained.

https://github.com/sifive/Kami

It does not contain any examples though. Most of the design examples should
work as is, but the proofs wont.

**Comment by command-paul** [comment]
Running into the same issues on the dsss-18 branch.

Missing deps on the sifive version ::
Fatal error: exception Sys_error("../bbv/theories: No such file or directory")

**Comment by vmurali** [comment]
For the sifive version, you need to have the bbv repository:

https://github.com/mit-plv/bbv

The directory structure must be:
<top-level-directory>
- Kami
- bbv

From the top-level-directory:
$ cd bbv; make -j; cd ..
$ cd Kami
$ make -j

**Comment by command-paul** [comment]
Thanks ! The make ran to completion on sifive/kami :)

**Comment by joonwonc** [comment]
I double-checked that both `coq-8.8` and `dsss-18` successfully compile with Coq 8.8.0.
Which version of Coq did you use to compile (e.g., 8.8.x)? (You can check by `which coqc`)
Even if the issue is closed, your answer would help us maintain the framework :)

**Comment by command-paul** [comment]
```bash
commandpaul@battlestation:/scratch/sivkami/Kami$ coqc --version
The Coq Proof Assistant, version 8.8.0 (July 2018)
compiled on Jul 30 2018 18:26:53 with OCaml 4.05.0

```

**Comment by joonwonc** [comment]
I'm now pretty sure you didn't try with a clean slate of `coq-8.8` or `dsss-18`. 
You got the error in `ParametricWf.v@L281` because in `master` a function is defined as `Fixpoint` which is actually not a recursive function. Coq 8.8 doesn't allow using the `Fixpoint` keyword if the function is not recursive.

Could you try to switch the branch to `coq-8.8` by doing `git checkout coq-8.8`, check that the normal `Definition` keyword is used at `ParametricWf.v@L281`, and try again to compile?

**Comment by command-paul** [comment]
Your right , Accidentally sneaked in a "-b" while checking out the 8.8 branch ! completely mislead me.
Apologies for the inconvenience of not having thoroughly eliminated that possibility. 

Still Running into 
```bash
ocamlbuild -use-ocamlfind -r Main.native
+ ocamlfind ocamlc -c -o PP.cmo PP.ml
File "PP.ml", line 2, characters 5-11:
Error: Unbound module Target
Command exited with code 2.
Compilation unsuccessful after building 3 targets (2 cached) in 00:00:00.
Makefile:9: recipe for target 'native' failed
make: *** [native] Error 10
```
while trying to build proc.bsv on both the  8.8 & dsss-18 branches

**Comment by joonwonc** [comment]
`coq-8.8` and `dsss-18` branches do not have the processor+memory case study so there's nothing to extract to Bluespec code.
The case study is currently not working in Coq 8.8, which is in our future work list, but I'm not sure that will be done shortly.
If you want to check Kami-to-Bluespec conversion, you have to compile in `master` with Coq 8.6.

**Comment by command-paul** [comment]
#### Thanks !
